travis:
  secure:
    BINSTAR_TOKEN: YY4aOub9iNQLBvSjz194svynwB3YAPNmAP6lgJx8EDjBJ1VNIxQ6Vr8guV7r+f6QF0BsPJvk6GzBzUYsgr72raCS8KM+8qQyD313Cl/QxAs8omOuf2THGCaocdrJpyaz14pFkOc0I8QmT24I+Uh81zb+ONZwqZadrMVMQNTSzXL1O7QD+xli5SB8c5ETmistxsAXuRfReVfk+5GJ/E09PtoulQc4tF73l/iZdQZmXgJphYZRycZ/uvzW5g74M3IKDqHTxwb2K2E6A6gubQpPAe9Czm4qkseE7HJaxpIdW2Gxo39WkBWq1nFySXPWV3PVofr9amElVSFoHunxCIu9rfGm6IFw+Li6d6yNgv0KQv3IkT+tAhZzWQweO8K5un5ec2f/aDFnoQjpvhMryXuRGY2JXJVEOfo3yKqXjzZ5AKHNvpJ1eEsVw5klUrQ8iQGQ+URcxs8ZROnqDeqXz3Hj0LDAEOZrE4TsGFmfyEgxSzeGGhO+vet9podsYdiYXA0k9AfIztxILYul+IB3LA1wnE8Kq+v4SOiGnnDoy2y6F6LP0AxiAtSj0Iw+TnWyzZ0U5KDjbJuLogWhVO5pUa5sO35TEX1bE+J4E2OMi1wlpGPzozxqjuiPiHBcC1Gw6JEdgelm2+bunYJ6L35nWTqUAWeuBSQSkHdka8DX7LfolP4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
