travis:
  secure:
    BINSTAR_TOKEN: pb3GUYT33qlPfhFCeBnTMGLIXfJYKmnbJgnaINtis/9/oCCem9DTy/RVyhfT8Bte8qrodeucbmos8q1WpQzR9m7t7dRDgQ6DNLlCbzWMYw8kVz+kc5rYoOztv3SKmRUStTDaNy6AoHEh0vcXFtQxsScpGnN52o4hmkn5t4ytl/Z24+iHlxNp99HM6zd5RGw8NlsJn9RTT6w/hBQqg7VUQYTwNnY6Qat8gh2Qwk4qOvrXYi9rERAGZ5ZGIQmpKqvWq7swubfAgyVp1zEWjusc4iOROGqQeuA/yOBDDByHQoNUkFs8d7EDMb2f00ECelbRWDLYnwb8sQoAa/bkU6c59HtvUgZpx6agyd5WA4h4QoN45ExsbcDxANe72kTU5aEwH9f5CaKC0sPl6RwLVyTEVHf8mzluK1hPFNr1KgdY5isgKRd+zTP5+n0S9i3WqwvdGULvMCuMe/PV3245ny6HIYrWxI2dWZiUURvR4pgaztQmpEs2gFik3HLLapdoKSNyH8kxCUYjwxFzErCYDNLi7MM+WDRUmnCh3p2DUXXiTUJvC1CU6wsnGufoTSQHR+C0i6jdrLruagCOPLdt9unvV1ZzTXesg6gyU84cUKWNCmkDqy+Mdq2kmEoebJNKCOBgQKEUIPCayHyI4H9KImvnXLyhNldUNgL0H94/Vw++00U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
